/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2016-12-17 02:00:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hgcontbad_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>HG ContBad</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<image src=\"MyServlet?image=h");
out.print(request.getAttribute("image"));
      out.write(".gif\">\r\n");
      out.write("\t<h2 style=\\\"font-family:'Lucida Console', monospace\\\"> ");
 out.println(request.getAttribute("guess")); 
      out.write("</h2>\r\n");
      out.write("\t<form action=\"MyServlet\" method=\"post\">\r\n");
      out.write("\t    <p>There are no ");
 out.println(request.getAttribute("lastGuess")); 
      out.write("'s.\r\n");
      out.write("\t    <input onkeypress=\"return onlyAlphabets(event,this);\" type=\"text\" name=\"guess\" /></p>\r\n");
      out.write("\t    <input style=\"display: none\" type=\"text\" name=\"time\" value=\"0\" />\r\n");
      out.write("\t\r\n");
      out.write("\t    <p>Submit button.\r\n");
      out.write("\t    <input type=\"submit\" name=\"submit\" value=\"submit\" /></p>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div id=\"timer\">You have been playing this game for ");
 out.println(request.getAttribute("time")); 
      out.write(" seconds...</div>\r\n");
      out.write("\t<form action=\"MyServlet\" method=\"post\">  \r\n");
      out.write("\t\t<button name=\"logout\" value=\"true\">Logout</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar time = ");
 out.println(request.getAttribute("time")); 
      out.write(" != null ? ");
 out.println(request.getAttribute("time")); 
      out.write(" : 0;\r\n");
      out.write("\t$(\"#submit-button\").prop(\"disabled\", true);\r\n");
      out.write("\t$(\"input[name=guess]\").change(function() {\r\n");
      out.write("\t\tif ($(\"input[name=guess]\").val().length > 0) {\r\n");
      out.write("\t\t\t$(\"#submit-button\").prop(\"disabled\", false);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#submit-button\").prop(\"disabled\", true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction onlyAlphabets(e, t) {\r\n");
      out.write("        try {\r\n");
      out.write("            if (window.event) {\r\n");
      out.write("                var charCode = window.event.keyCode;\r\n");
      out.write("            }\r\n");
      out.write("            else if (e) {\r\n");
      out.write("                var charCode = e.which;\r\n");
      out.write("            }\r\n");
      out.write("            else { return true; }\r\n");
      out.write("            if ((charCode > 64 && charCode < 91) || (charCode > 96 && charCode < 123))\r\n");
      out.write("                return true;\r\n");
      out.write("            else\r\n");
      out.write("                return false;\r\n");
      out.write("        }\r\n");
      out.write("        catch (err) {\r\n");
      out.write("            alert(err.Description);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"MyServlet?js=timer.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
